{{- if .Values.ingress.enabled -}}
{{- $fullname := include "idea-board.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "idea-board.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - {{- with .Values.ingress.host }}
      host: {{ . | quote }}
      {{- end }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}-backend
                port: { name: http }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}-frontend
                port: { name: http }
{{- end }}
